### ISSUE TITLE
Allow « and » as program delimiters.

### ISSUE THREAD

**Issue by gwenhael-le-moine** [louis-/rpn#220]

**Comment by gwenhael-le-moine** [comment]
After trying a bit to code this I'm sure it implies making parsing utf-8-aware.

**Comment by louisrubet** [comment]
(sorry for the delay)
You are correct. Although utf-8 strings can be used as symbols or strings in rpn, the parser breaks the delimiters as single 8 bits characters. Probably the parser (at least the lexer part) should be reworked.
```
rpn> «» 👨
2> '«»'
1> '👨'
rpn> 
```

**Comment by louisrubet** [comment]
Realized by #218
